name: make comment for staged-recipes linter

on:
  workflow_run:
    workflows: ["staged-recipes linter"]
    types:
      - completed

jobs:
  make-comment:
    name: make comment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: install code
        uses: mamba-org/setup-micromamba@068f1ab4b37ed9b3d9f73da7db90a0cda0a48d29
        with:
          environment-name: lint
          condarc: |
            show_channel_urls: true
            channel_priority: strict
            channels:
              - conda-forge
          create-args: >-
            conda-smithy
            pygithub
            requests

      - name: make comment
        run: |
          python .github/workflows/scripts/linter_make_comment.py \
            --head-repo-owner=${{ github.event.workflow_run.head_repository.owner.login }} \
            --workflow-run-id=${{ github.event.workflow_run.id }} \
            --head-sha=${{ github.event.workflow_run.head_sha }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
